version: '3.1'

services:
  mldonkey:
    build:
      tags:
        #- mldonkey:lastest
        #- mldonkey:staging
        - mldonkey:test
    #image: carlonluca/mldonkey
    #image: mldonkey:staging
    env_file: env
    volumes:
    - ./data:/var/lib/mldonkey
    #- ./temp:/var/lib/mldonkey/temp
    ports:
    - "0.0.0.0:4000:4000"
    - "0.0.0.0:4001:4001"
    - "0.0.0.0:4080:4080"
    - "0.0.0.0:19040:19040"
    - "0.0.0.0:19044:19044"

# volumes:
#   data:
#     driver: local
  # temp:
  #   driver: local

